# Import custom component from GitHub
# Import custom components...
external_components:
  - source: github://beormund/esphome-samsung-nasa@main
    components: [samsung_nasa]

esphome:
  name: samsung_nasa
  friendly_name: Heat Pump
  min_version: 2025.7.0

esp32:
  board: m5stack-atom

# Enable logging
logger:
  logs:
    component: ERROR

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: web_server
  - platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# To have a "next url" for improv serial
web_server:
  port: 80
  version: 3
  log: true
  local: true

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 9600
  parity: EVEN

## SAMSUNG NASA CONFIGURATION
samsung_nasa:
  debug_log_messages: false
  debug_log_undefined_messages: false
  nasa_client: {}
  devices:
   - address: 20.00.00
     id: nasa_device_1
   - address: 10.00.00
     id: nasa_device_2

number:
  - platform: samsung_nasa
    message: 0x4201
    name: Zone 1 Target Temp
    internal: true
    nasa_device_id: nasa_device_1
    id: zone_target_temp
  - platform: samsung_nasa
    message: 0x42D6
    name: Zone 2 Target Temp
    internal: true
    nasa_device_id: nasa_device_1
    id: zone2_target_temp
  - platform: samsung_nasa
    message: 0x4235
    name: DHW Target Temperature
    internal: true
    nasa_device_id: nasa_device_1
    id: hot_water_target_temp
  - platform: samsung_nasa
    fsv: 2011
    nasa_device_id: nasa_device_1
    name: Water Law (Outdoor Temp) High
    id: fsv_2011
  - platform: samsung_nasa
    fsv: 2012
    nasa_device_id: nasa_device_1
    name: Water Law (Outdoor Temp) Low
    id: fsv_2012
  - platform: samsung_nasa
    fsv: 2021
    nasa_device_id: nasa_device_1
    name: Water Law (Flow Temp) High
    id: fsv_2021
  - platform: samsung_nasa
    fsv: 2022
    nasa_device_id: nasa_device_1
    name: Water Law (Flow Temp) Low
    id: fsv_2022

select:
  - platform: samsung_nasa
    message: 0x4066
    nasa_device_id: nasa_device_1
    name: Hot Water Mode
    id: hotwater_mode

switch:
  - platform: samsung_nasa
    message: 0x4065
    nasa_device_id: nasa_device_1
    name: "DHW Power"
    internal: true
    id: dhw_power_switch
  - platform: samsung_nasa
    message: 0x4000
    nasa_device_id: nasa_device_1
    name: Zone 1 Power
    internal: true
    id: zone_power
  - platform: samsung_nasa
    message: 0x411E
    nasa_device_id: nasa_device_1
    name: Zone 2 Power
    internal: true
    id: zone2_power

sensor:
  - platform: samsung_nasa
    message: 0x4237
    nasa_device_id: nasa_device_1
    name: "DHW Temperature"
    internal: true
    id: hot_water_current_temp
  - platform: samsung_nasa
    message: 0x4203
    nasa_device_id: nasa_device_1
    name: "Zone 1 Indoor Temp"
    internal: true
    id: zone_room_temp
  - platform: samsung_nasa
    message: 0x42D4
    nasa_device_id: nasa_device_1
    name: "Zone 2 Indoor Temp"
    internal: true
    id: zone2_room_temp
  - platform: samsung_nasa
    message: 0x4238
    nasa_device_id: nasa_device_1
    name: Flow Temperature
    id: zone_flow_temp
  - platform: samsung_nasa
    message: 0x4427
    nasa_device_id: nasa_device_1
    name: Heat Pump Produced Energy
    # 0x408A: ENUM_IN_2WAY_VALVE
    # On MIM board  2-way valves 
    # are connected to Pins B9/B10,
    # B13/B14 (switched live output)
    #        0    1    2   3
    #  B09  OFF  ON   OFF  ON
    #  B10  ON   OFF  ON   OFF
    #  B13  OFF  OFF  ON   ON
    #. B14  ON   ON   OFF  OFF    
  - platform: samsung_nasa
    message: 0x408A
    nasa_device_id: nasa_device_1
    name: 2-Way Valve
    internal: true
    id: two_way_valve 
    # 0x4089
    # 0 = off; 1 =  on
  - platform: samsung_nasa
    message: 0x4089
    nasa_device_id: nasa_device_1
    name: Primary Water Pump
    internal: true
    id: primary_water_pump
    # 0x4067
    # 0 = room; 1 = tank
  - platform: samsung_nasa
    message: 0x4067
    nasa_device_id: nasa_device_1
    name: 3-Way Valve
    internal: true
    id: three_way_valve 
  - platform: samsung_nasa
    message: 0x8235
    nasa_device_id: nasa_device_2
    name: Error Code
  - platform: samsung_nasa
    message: 0x8414
    nasa_device_id: nasa_device_2
    name: "Heat Pump Cumulative Energy"
  - platform: samsung_nasa
    message: 0x8413
    nasa_device_id: nasa_device_2
    name: Heat Pump Instantaneous Power
  - platform: samsung_nasa
    message: 0x8204
    nasa_device_id: nasa_device_2
    name: Outdoor Temperature

climate:
  - platform: samsung_nasa
    name: Hot Water
    id: climate_hot_water
    power_switch_id: dhw_power_switch
    current_temp_sensor_id: hot_water_current_temp
    target_temp_number_id: hot_water_target_temp
    custom_preset_select_id: hotwater_mode
    action_mode_sensor:
      id: three_way_valve
      mappings:
        0: CLIMATE_ACTION_IDLE
        1: CLIMATE_ACTION_HEATING
    visual:
      min_temperature: 30
      max_temperature: 60
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1

  - platform: samsung_nasa
    name: Ground Floor Heating
    id: climate_ground_floor
    power_switch_id: zone_power
    current_temp_sensor_id: zone_room_temp
    target_temp_number_id: zone_target_temp
    action_mode_sensor:
      id: two_way_valve
      mappings:
        0: CLIMATE_ACTION_HEATING
        1: CLIMATE_ACTION_IDLE
        2: CLIMATE_ACTION_HEATING
        3: CLIMATE_ACTION_IDLE
    visual:
      min_temperature: 16
      max_temperature: 30
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1

  - platform: samsung_nasa
    name: First Floor Heating
    id: climate_first_floor
    power_switch_id: zone2_power
    current_temp_sensor_id: zone2_room_temp
    target_temp_number_id:  zone2_target_temp
    action_mode_sensor:
      id: two_way_valve
      mappings:
        0: CLIMATE_ACTION_HEATING
        1: CLIMATE_ACTION_HEATING
        2: CLIMATE_ACTION_IDLE
        3: CLIMATE_ACTION_IDLE
    visual:
      min_temperature: 16
      max_temperature: 30
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1        

interval:
  - interval: 30min
    startup_delay: 30s
    then:
      # This automation action requests NASA to read
      # the NASA messages associated with the component ids
      # Only Sensor, Switch, Number & Select components with
      # the samsung_nasa framework are accepted in the list
      # of ids (can be one or more). You can specify any
      # number of components - they will be batched into
      # groups of up to 10 messages before being sent,
      - samsung_nasa.request_read:
          id: [fsv_2011, fsv_2012, fsv_2021, fsv_2022]

button:
  - platform: template
    name: Request
    entity_category: config
    on_press:
      - samsung_nasa.request_read:
          id: [fsv_2011, fsv_2012, fsv_2021, fsv_2022]

